### ISSUE TITLE
sparql-doc raises TypeError

### ISSUE THREAD

**Issue by ziodave** [ldodds/sparql-doc#18]
Hello,

When I run `sparql-doc` I get the following error:

```
.rvm/gems/ruby-2.0.0-p247/gems/sparql-doc-0.0.4/lib/sparql-doc/generator.rb:21:in `join': no implicit conversion of nil into String (TypeError)
     [exec] 	from ~/.rvm/gems/ruby-2.0.0-p247/gems/sparql-doc-0.0.4/lib/sparql-doc/generator.rb:21:in `parse_package'
     [exec] 	from ~/.rvm/gems/ruby-2.0.0-p247/gems/sparql-doc-0.0.4/lib/sparql-doc/generator.rb:12:in `initialize'
     [exec] 	from ~/.rvm/gems/ruby-2.0.0-p247/gems/sparql-doc-0.0.4/bin/sparql-doc:6:in `new'
     [exec] 	from ~/.rvm/gems/ruby-2.0.0-p247/gems/sparql-doc-0.0.4/bin/sparql-doc:6:in `<top (required)>'
     [exec] 	from ~/.rvm/gems/ruby-2.0.0-p247/bin/sparql-doc:23:in `load'
     [exec] 	from ~/.rvm/gems/ruby-2.0.0-p247/bin/sparql-doc:23:in `<main>'
     [exec] 	from ~/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
     [exec] 	from ~/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'
```

How can I fix it, or how can I debug it?

Thanks!

**Comment by ziodave** [comment]
The same error happens with ruby-1.9.3:

```
sparql-doc:
     [exec] ~/.rvm/gems/ruby-1.9.3-p551/gems/sparql-doc-0.0.4/lib/sparql-doc/generator.rb:21:in `join': can't convert nil into String (TypeError)
     [exec] 	from ~/.rvm/gems/ruby-1.9.3-p551/gems/sparql-doc-0.0.4/lib/sparql-doc/generator.rb:21:in `parse_package'
     [exec] 	from ~/.rvm/gems/ruby-1.9.3-p551/gems/sparql-doc-0.0.4/lib/sparql-doc/generator.rb:12:in `initialize'
     [exec] 	from ~/.rvm/gems/ruby-1.9.3-p551/gems/sparql-doc-0.0.4/bin/sparql-doc:6:in `new'
     [exec] 	from ~/.rvm/gems/ruby-1.9.3-p551/gems/sparql-doc-0.0.4/bin/sparql-doc:6:in `<top (required)>'
     [exec] 	from ~/.rvm/gems/ruby-1.9.3-p551/bin/sparql-doc:23:in `load'
     [exec] 	from ~/.rvm/gems/ruby-1.9.3-p551/bin/sparql-doc:23:in `<main>'
     [exec] 	from ~/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
     [exec] 	from ~/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'```

**Comment by ziodave** [comment]
Ok, I found the issue which was caused by `sparql-doc` being launched from an _ant task_ with `/bin/sh -c`. Launching it directly works. Thanks and sorry :-)
